-- Japan dealer stock — goo-net import
-- Generated by scripts/goonet-seed.mjs from
-- scripts/fixtures/goonet-capture-2026-08-31.json
-- Captured from https://www.goo-net.com/usedcar/price-100-300/ on 2026-08-31.
--
-- Safe to run again: rows are keyed on goonet_id, so a re-run refreshes the
-- cars instead of duplicating them. Run AFTER supabase/SETUP-EVERYTHING.sql.

insert into public.japan_dealer_stock (
  goonet_id, stock_no, make, model, year, km, fuel, body, price_jpy, price_usd, price, image, images, grade, status, location, tr, eng, vendor, goonet_url, photo_count, quality_score, available, promoted, imported_at, last_seen_at, updated_at
) values
  ('988026082700209395001', '988026082700209395001', 'Mazda', 'Atenza', 2019, '47000', 'Diesel', 'Sedan', 1999000, 13593, '$13,593', 'https://picture1.goo-net.com/9880260827/00209395/Q/98802608270020939500100.jpg', '["https://picture1.goo-net.com/9880260827/00209395/Q/98802608270020939500100.jpg","https://picture1.goo-net.com/020/0209395/Q/0209395A20260826D00101.jpg","https://picture1.goo-net.com/020/0209395/Q/0209395A20260826D00102.jpg","https://picture1.goo-net.com/020/0209395/Q/0209395A20260826D00103.jpg"]'::jsonb, '3.5', 'New Arrival', '愛知県', 'MTモード付きAT', '2,200cc', 'Goo-net', 'https://www.goo-net.com/usedcar/spread/goo/15/988026082700209395001.html', 4, 80, true, 'none', '2026-08-31T01:35:19.708Z', '2026-08-31T01:35:19.708Z', '2026-08-31T01:35:19.708Z'),
  ('988026082600208975002', '988026082600208975002', 'Toyota', 'Corolla Fielder', 2017, '94000', 'Hybrid', 'Wagon', 1140000, 7752, '$7,752', 'https://picture1.goo-net.com/9880260826/00208975/Q/98802608260020897500200.jpg', '["https://picture1.goo-net.com/9880260826/00208975/Q/98802608260020897500200.jpg","https://picture1.goo-net.com/020/0208975/Q/0208975A20260825D00201.jpg","https://picture1.goo-net.com/020/0208975/Q/0208975A20260825D00202.jpg","https://picture1.goo-net.com/020/0208975/Q/0208975A20260825D00203.jpg"]'::jsonb, '3', 'New Arrival', '岐阜県', 'AT', '1,500cc', 'Goo-net', 'https://www.goo-net.com/usedcar/spread/goo/15/988026082600208975002.html', 4, 80, true, 'none', '2026-08-31T01:35:19.708Z', '2026-08-31T01:35:19.708Z', '2026-08-31T01:35:19.708Z'),
  ('700054106930260526003', '700054106930260526003', 'Toyota', 'Prius', 2017, '82000', 'Hybrid', 'Sedan', 1312000, 8922, '$8,922', 'https://picture1.goo-net.com/7000541069/30260526/Q/70005410693026052600300.jpg', '["https://picture1.goo-net.com/7000541069/30260526/Q/70005410693026052600300.jpg","https://picture1.goo-net.com/054/0541069/Q/0541069A30260526W00301.jpg","https://picture1.goo-net.com/054/0541069/Q/0541069A30260526W00305.jpg","https://picture1.goo-net.com/054/0541069/Q/0541069A30260526W00313.jpg"]'::jsonb, '4', 'New Arrival', '埼玉県', 'インパネAT', '1,800cc', 'Goo-net', 'https://www.goo-net.com/usedcar/spread/goo/13/700054106930260526003.html', 4, 80, true, 'none', '2026-08-31T01:35:19.708Z', '2026-08-31T01:35:19.708Z', '2026-08-31T01:35:19.708Z'),
  ('988026082600208975003', '988026082600208975003', 'Honda', 'N-BOX', 2022, '26000', 'Petrol', 'Kei', 1640000, 11152, '$11,152', 'https://picture1.goo-net.com/9880260826/00208975/Q/98802608260020897500300.jpg', '["https://picture1.goo-net.com/9880260826/00208975/Q/98802608260020897500300.jpg","https://picture1.goo-net.com/020/0208975/Q/0208975A20260825D00301.jpg","https://picture1.goo-net.com/020/0208975/Q/0208975A20260825D00302.jpg","https://picture1.goo-net.com/020/0208975/Q/0208975A20260825D00303.jpg"]'::jsonb, '4', 'New Arrival', '岐阜県', 'インパネAT', '660cc', 'Goo-net', 'https://www.goo-net.com/usedcar/spread/goo/15/988026082600208975003.html', 4, 80, true, 'none', '2026-08-31T01:35:19.708Z', '2026-08-31T01:35:19.708Z', '2026-08-31T01:35:19.708Z'),
  ('965026083000203158006', '965026083000203158006', 'Mazda', 'Roadster', 2018, '33000', 'Petrol', 'Coupe', 2790000, 18972, '$18,972', 'https://picture1.goo-net.com/9650260830/00203158/Q/96502608300020315800600.jpg', '["https://picture1.goo-net.com/9650260830/00203158/Q/96502608300020315800600.jpg","https://picture1.goo-net.com/020/0203158/Q/0203158A20260829Q00601.jpg","https://picture1.goo-net.com/020/0203158/Q/0203158A20260829Q00602.jpg","https://picture1.goo-net.com/020/0203158/Q/0203158A20260829Q00603.jpg"]'::jsonb, '4', 'New Arrival', '愛知県', 'MT6速', '1,500cc', 'Goo-net', 'https://www.goo-net.com/usedcar/spread/goo/15/965026083000203158006.html', 4, 80, true, 'none', '2026-08-31T01:35:19.708Z', '2026-08-31T01:35:19.708Z', '2026-08-31T01:35:19.708Z'),
  ('988026072100208975003', '988026072100208975003', 'Honda', 'Freed', 2023, '21000', 'Hybrid', 'MPV', 2640000, 17952, '$17,952', 'https://picture1.goo-net.com/9880260721/00208975/Q/98802607210020897500300.jpg', '["https://picture1.goo-net.com/9880260721/00208975/Q/98802607210020897500300.jpg","https://picture1.goo-net.com/020/0208975/Q/0208975A20260720D00301.jpg","https://picture1.goo-net.com/020/0208975/Q/0208975A20260720D00302.jpg","https://picture1.goo-net.com/020/0208975/Q/0208975A20260720D00303.jpg"]'::jsonb, '4', 'New Arrival', '岐阜県', 'インパネAT', '1,500cc', 'Goo-net', 'https://www.goo-net.com/usedcar/spread/goo/15/988026072100208975003.html', 4, 80, true, 'none', '2026-08-31T01:35:19.708Z', '2026-08-31T01:35:19.708Z', '2026-08-31T01:35:19.708Z'),
  ('965026082400401948004', '965026082400401948004', 'Toyota', 'Noah', 2019, '85000', 'Petrol', 'MPV', 2110000, 14348, '$14,348', 'https://picture1.goo-net.com/9650260824/00401948/Q/96502608240040194800400.jpg', '["https://picture1.goo-net.com/9650260824/00401948/Q/96502608240040194800400.jpg","https://picture1.goo-net.com/040/0401948/Q/0401948A20260823Q00401.jpg","https://picture1.goo-net.com/040/0401948/Q/0401948A20260823Q00402.jpg","https://picture1.goo-net.com/040/0401948/Q/0401948A20260823Q00403.jpg"]'::jsonb, '4', 'New Arrival', '茨城県', 'CVT', '2,000cc', 'Goo-net', 'https://www.goo-net.com/usedcar/spread/goo/12/965026082400401948004.html', 4, 80, true, 'none', '2026-08-31T01:35:19.708Z', '2026-08-31T01:35:19.708Z', '2026-08-31T01:35:19.708Z'),
  ('988026082700208975001', '988026082700208975001', 'Toyota', 'Alphard', 2017, '77000', 'Petrol', 'MPV', 1990000, 13532, '$13,532', 'https://picture1.goo-net.com/9880260827/00208975/Q/98802608270020897500100.jpg', '["https://picture1.goo-net.com/9880260827/00208975/Q/98802608270020897500100.jpg","https://picture1.goo-net.com/020/0208975/Q/0208975A20260826D00101.jpg","https://picture1.goo-net.com/020/0208975/Q/0208975A20260826D00102.jpg","https://picture1.goo-net.com/020/0208975/Q/0208975A20260826D00103.jpg"]'::jsonb, '4', 'New Arrival', '岐阜県', 'インパネAT', '2,500cc', 'Goo-net', 'https://www.goo-net.com/usedcar/spread/goo/15/988026082700208975001.html', 4, 80, true, 'none', '2026-08-31T01:35:19.708Z', '2026-08-31T01:35:19.708Z', '2026-08-31T01:35:19.708Z')
on conflict (goonet_id) do update set
  make          = excluded.make,
  model         = excluded.model,
  year          = excluded.year,
  km            = excluded.km,
  fuel          = excluded.fuel,
  body          = excluded.body,
  price_jpy     = excluded.price_jpy,
  price_usd     = excluded.price_usd,
  price         = excluded.price,
  image         = excluded.image,
  images        = excluded.images,
  grade         = excluded.grade,
  location      = excluded.location,
  tr            = excluded.tr,
  eng           = excluded.eng,
  goonet_url    = excluded.goonet_url,
  photo_count   = excluded.photo_count,
  quality_score = excluded.quality_score,
  last_seen_at  = excluded.last_seen_at,
  updated_at    = excluded.updated_at;
