#!/usr/bin/env node
// Turn a captured goo-net batch into the exact rows the scheduled importer
// writes to `japan_dealer_stock`, then either print them, emit SQL, or upsert
// them into Supabase.
//
//   node scripts/goonet-seed.mjs                 print what would be imported
//   node scripts/goonet-seed.mjs --sql           (re)write supabase/japan-stock-seed.sql
//   SUPABASE_URL="https://xxx.supabase.co" \
//   SUPABASE_SERVICE_ROLE_KEY="eyJ..." \
//   node scripts/goonet-seed.mjs --push          upsert into japan_dealer_stock
//
// The point of running the capture through goonet-core (rather than
// hand-writing rows) is that the seed and the live importer cannot drift: same
// price maths, same make/model detection, same quality gate.
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import {
  manToYen, yenToUsd, usdText, kmToNumber, detectMake, detectModel, qualityScore,
  formatEngine
} from './goonet-core.mjs';

export const CAPTURE_FILE = fileURLToPath(new URL('./fixtures/goonet-capture-2026-08-31.json', import.meta.url));

export function readCapture(file = CAPTURE_FILE) {
  return JSON.parse(readFileSync(file, 'utf8'));
}

/** Same grade maths the importer uses: the mean of the 外装/内装 ratings. */
export function gradeFrom(ext, int) {
  if (!ext || !int) return null;
  return String(Math.round(((ext + int) / 2) * 2) / 2);
}

export function buildSeedRows(capture, { minPhotos = 4, importedAt = new Date().toISOString() } = {}) {
  const cars = Array.isArray(capture) ? capture : (capture?.cars || []);
  return cars.map(c => {
    const make = detectMake(c.make_jp || c.title) || 'Unknown';
    const model = detectModel(c.title, make) || 'Car';
    const priceJpy = manToYen(c.price_man);
    const images = (c.images || []).filter(Boolean);
    const car = {
      make, model, year: c.year || null, km: kmToNumber(c.km),
      // fuel/body are the curator's classification (goo-net prints them on the
      // detail page only) — the gate must judge the row that is written.
      fuel: c.fuel || null, body: c.body || null,
      price_jpy: priceJpy, price_usd: yenToUsd(priceJpy), price: usdText(yenToUsd(priceJpy)),
      image: images[0] || null, images, photo_count: images.length,
      ext_rating: c.ext || null, int_rating: c.int || null,
      repair_history: c.repair ? (String(c.repair).includes('あり') ? 'Yes' : 'No') : null
    };
    const q = qualityScore(car, { minPhotos });
    return {
      goonet_id: String(c.goonet_id),
      stock_no: String(c.goonet_id),
      make, model,
      year: car.year,
      km: car.km,
      fuel: c.fuel || null,
      body: c.body || null,
      price_jpy: car.price_jpy,
      price_usd: car.price_usd,
      price: car.price,
      total_price_jpy: manToYen(c.total_man),
      image: car.image,
      images,
      grade: gradeFrom(c.ext, c.int),
      status: 'New Arrival',
      location: c.pref || 'Japan',
      tr: c.tr || null,
      eng: formatEngine(c.eng),
      repair_history: car.repair_history,
      vendor: 'Goo-net',
      goonet_url: c.url,
      photo_count: car.photo_count,
      quality_score: q.score,
      quality_pass: q.pass,
      quality_reasons: q.reasons,
      shop: c.shop || null,
      available: true,
      promoted: 'none',
      imported_at: importedAt,
      last_seen_at: importedAt,
      updated_at: importedAt
    };
  });
}

const SQL_COLUMNS = [
  'goonet_id', 'stock_no', 'make', 'model', 'year', 'km', 'fuel', 'body',
  'price_jpy', 'price_usd', 'price', 'image', 'images', 'grade', 'status',
  'location', 'tr', 'eng', 'vendor', 'goonet_url', 'photo_count',
  'quality_score', 'available', 'promoted', 'imported_at', 'last_seen_at', 'updated_at'
];

const lit = v => v === null || v === undefined ? 'null'
  : typeof v === 'number' ? String(v)
  : typeof v === 'boolean' ? String(v)
  : typeof v === 'object' ? `'${JSON.stringify(v).replace(/'/g, "''")}'::jsonb`
  : `'${String(v).replace(/'/g, "''")}'`;

export function seedSql(rows, capture) {
  const values = rows.map(r => '  (' + SQL_COLUMNS.map(c => lit(r[c])).join(', ') + ')').join(',\n');
  return `-- Japan dealer stock — goo-net import
-- Generated by scripts/goonet-seed.mjs from
-- scripts/fixtures/goonet-capture-${(capture?.captured_at || 'capture').replace(/-/g, '-')}.json
-- Captured from ${(capture && capture.source) || 'goo-net'} on ${(capture && capture.captured_at) || 'unknown date'}.
--
-- Safe to run again: rows are keyed on goonet_id, so a re-run refreshes the
-- cars instead of duplicating them. Run AFTER supabase/SETUP-EVERYTHING.sql.

insert into public.japan_dealer_stock (
  ${SQL_COLUMNS.join(', ')}
) values
${values}
on conflict (goonet_id) do update set
  make          = excluded.make,
  model         = excluded.model,
  year          = excluded.year,
  km            = excluded.km,
  fuel          = excluded.fuel,
  body          = excluded.body,
  price_jpy     = excluded.price_jpy,
  price_usd     = excluded.price_usd,
  price         = excluded.price,
  image         = excluded.image,
  images        = excluded.images,
  grade         = excluded.grade,
  location      = excluded.location,
  tr            = excluded.tr,
  eng           = excluded.eng,
  goonet_url    = excluded.goonet_url,
  photo_count   = excluded.photo_count,
  quality_score = excluded.quality_score,
  last_seen_at  = excluded.last_seen_at,
  updated_at    = excluded.updated_at;
`;
}

// ---- CLI -------------------------------------------------------------------
const isMain = process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1];

if (isMain) {
  const capture = readCapture();
  const rows = buildSeedRows(capture);
  const sqlPath = fileURLToPath(new URL('../supabase/japan-stock-seed.sql', import.meta.url));

  console.log(`\n  goo-net capture ${capture.captured_at} — ${rows.length} cars from ${capture.source}\n`);
  for (const r of rows) {
    console.log(`  ${r.quality_pass ? '+' : '–'} ${r.year} ${r.make} ${r.model} · ${r.price} (${r.price_jpy?.toLocaleString('en-US')} yen)`
      + ` · ${r.km} km · grade ${r.grade} · ${r.photo_count} photos · score ${r.quality_score}`
      + (r.quality_reasons.length ? ` [${r.quality_reasons.join(', ')}]` : ''));
  }

  if (process.argv.includes('--sql') || process.argv.includes('--push')) {
    writeFileSync(sqlPath, seedSql(rows, capture));
    console.log(`\n  wrote ${sqlPath}`);
  }

  if (process.argv.includes('--push')) {
    const url = process.env.SUPABASE_URL;
    const key = process.env.SUPABASE_SERVICE_ROLE_KEY;
    if (!url || !key) {
      console.error('\n  --push needs SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY.\n');
      process.exit(1);
    }
    const { createClient } = await import('@supabase/supabase-js');
    const db = createClient(url, key, { auth: { persistSession: false } });
    const payload = rows.map(({ total_price_jpy, quality_pass, quality_reasons, repair_history, shop, ...row }) => row);
    const { error } = await db.from('japan_dealer_stock').upsert(payload, { onConflict: 'goonet_id' });
    if (error) { console.error('  ✗ upsert failed:', error.message); process.exit(1); }
    console.log(`  ✓ ${payload.length} cars upserted into japan_dealer_stock.\n`);
    process.exit(0);
  }

  console.log('\n  Nothing written. Use --sql to emit SQL or --push to upsert into Supabase.\n');
}
