import assert from 'node:assert/strict';
import { readMachineryRows, machineryVisibility } from '../api/_machinery.js';
import { runScraper } from '../api/_machinery-scraper.js';
import { syncFailure } from './check-sync-report.mjs';
const seed = Array.from({length:1201}, (_,i) => ({id:String(i),ref:`AR7-MC-${i}`,type:'Excavators',brand:'Sany',model:'SY215',source_url:`https://supplier.example/${i}`,published:i%2===0,status:i===1?'Archived':'Available', price_usd:null}));
let reads=0;
const db={from(){let from=0,to=0;return {select(){return this},order(){return this},range(a,b){from=a;to=b;return this},then(resolve){reads++;return resolve({data:seed.slice(from,to+1),error:null})}}}};
const rows=await readMachineryRows(db);
assert.equal(rows.length,1201);
assert.equal(reads,3);
const audit=machineryVisibility(rows);
assert.equal(audit.imported,1201);
assert.equal(audit.hiddenImported,600);
assert.equal(audit.items[1].visibility,'archived');
assert.equal(audit.items[3].invalid.length,0, 'missing price, photos, year and hours must not block restoring a valid listing');
assert.equal(audit.items[2].href,'/machinery/excavators/AR7-MC-2');
const broken={from(){return {select(){return this},order(){return this},then(resolve){return resolve({data:null,error:{code:'42P01',message:'machinery table missing'}})}}}};
await assert.rejects(readMachineryRows(broken), /machinery table missing/);
await assert.rejects(runScraper(broken, {limit:8}), /machinery table missing/);
assert.match(syncFailure({error:'Sync failed', details:'machinery table missing',code:'42P01'}), /42P01/);
assert.equal(syncFailure({job:'machinery-audit', readOnly:true,inventory:audit}),null);
console.log('Machinery visibility: pagination, hidden/archived imports, schema failure and read-only audit checks passed');
